# -*- coding: utf-8 -*-
"""DTU1_spp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zaben3GfqVSRVUG6ceVG22a0A9f04JP7
"""

#1
def greet():
    print("Hello World")
greet()

#2
def goldilocks(bed_length):
    if bed_length<140:
        print("to small")
    elif bed_length>150:
        print("to large")
    else:
        print("right length")
goldilocks(132)
goldilocks(151)
goldilocks(142)



#3
def square_list(numbers):
    squared_numbered = []
    for num in numbers:
        squared_numbered.append(num**2)
    return squared_numbered
square_list([1,2,3,4])
square_list([-1,2,6,-4])

#4
def fibonacci_stop(max_num):
    fibonacci_numbers = [1,1]
    while True:
        next_value = fibonacci_numbers[-1] + fibonacci_numbers[-2]
        if next_value> max_num:
            break
        fibonacci_numbers.append(next_value)
    return fibonacci_numbers
fibonacci_stop(20)
fibonacci_stop(50)